In [14]:
import pandas as pd

In [15]:
df = pd.read_excel('data/raw_data.xlsx', sheet_name='Macroeconomic variables')
df = df.rename(columns={'Unnamed: 0': 'quarter'})

In [16]:
df['quarter'] = pd.PeriodIndex(
    df['quarter'].str.replace(r'Q([1-4]) (\d{4})', r'\2Q\1', regex=True),
    freq='Q'
)

In [17]:
df = df[['quarter', 'UK real GDP', 'UK CPI', 'UK unemployment rate', 'UK aggregate retail deposits', 'Bank Rate']]
df = df.set_index('quarter')

In [18]:
df

,UK real GDP,UK CPI,UK unemployment rate,UK aggregate retail deposits,Bank Rate
quarter,,,,,
2000Q1,444540,53.3,5.8,5.5,5.87
2000Q2,447825,53.8,5.5,4.9,6.00
2000Q3,450688,53.8,5.3,6.0,6.00
2000Q4,453447,54.1,5.2,6.1,6.00
2001Q1,457680,53.8,5.1,7.7,5.86
...,...,...,...,...,...
2023Q4,632365,97.6,3.9,1.0,5.25
2024Q1,637729,97.8,4.3,2.4,5.25
2024Q2,640592,99.0,4.2,3.5,5.25
2024Q3,640417,99.2,4.3,4.8,5.09
2024Q4,641065,100.0,4.4,5.3,4.85

In [19]:
df['cpi_rate'] = ((df['UK CPI'] - df['UK CPI'].shift(4)) / df['UK CPI'].shift(4)) * 100

In [20]:
df = df.rename(columns={
    'UK real GDP': 'real_GDP',
    'UK CPI': 'cpi_level',
    'UK unemployment rate': 'unemp_rate',
    'UK aggregate retail deposits': 'agg_deposits',
    'Bank Rate': 'base_rate'
})

In [21]:
df

         real_GDP  cpi_level  unemp_rate  agg_deposits  base_rate  cpi_rate
quarter
2000Q1     444540       53.3         5.8           5.5       5.87       NaN
2000Q2     447825       53.8         5.5           4.9       6.00       NaN
2000Q3     450688       53.8         5.3           6.0       6.00       NaN
2000Q4     453447       54.1         5.2           6.1       6.00       NaN
2001Q1     457680       53.8         5.1           7.7       5.86  0.938086
...           ...        ...         ...           ...        ...       ...
2023Q4     632365       97.6         3.9           1.0       5.25  4.162220
2024Q1     637729       97.8         4.3           2.4       5.25  3.492063
2024Q2     640592       99.0         4.2           3.5       5.25  2.167183
2024Q3     640417       99.2         4.3           4.8       5.09  2.057613
2024Q4     641065      100.0         4.4           5.3       4.85  2.459016

[100 rows x 6 columns]

In [22]:
df.to_csv('data/data.csv')